--创建员工管理数据库
create TABLE W_STAFF
(
STAFF_ID VARCHAR(20) NOT NULL,
STAFF_NAME VARCHAR(20) NOT NULL,
STAFF_GENDER enum('男','女'),
STAFF_POSITION VARCHAR(50),
STAFF_POWER INT(2) NOT NULL,
PRIMARY KEY(STAFF_ID)
)
--创建EasyUI后台菜单按钮
create TABLE W_B_MENUS
(
ID VARCHAR(20) NOT NULL,
PID VARCHAR(20) NULL,
TEXT VARCHAR(50) NULL,
STATUS VARCHAR(20) NULL,
URL VARCHAR(100) NULL,
PRIMARY KEY(ID),
UNIQUE (TEXT)
)
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('1','','员工管理','CLOSED','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('2','','数据管理','CLOSED','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('11','1','员工权限管理','','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('12','1','员工信息管理','','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('21','2','数据信息导入','','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('22','2','数据信息导出','','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('111','11','添加新员工','','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('112','11','修改员工权限','','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('113','11','删除员工','','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('121','12','查询员工信息','','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('122','12','添加员工信息','','');
INSERT INTO W_B_MENUS (ID,PID,TEXT,STATUS,URL)VALUES('123','12','删除员工信息','','');